version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - brackets

  php:
    build:
      context: .
      dockerfile: ./server/docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./server/src:/var/www/html
    networks:
      - brackets

  db:
    image: mysql
    restart: always
    ports:
      - "5432:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: 'aspro'
    networks:
      - brackets

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "7000:80"
    networks:
      - brackets

networks:
  brackets:
    driver: bridge